#!/usr/bin/env python3
"""
email_renderer.py — Convert a markdown briefing note to HTML email format.

Strips Obsidian-specific syntax, converts markdown to HTML, and wraps in
a responsive email template.

Usage:
    python email_renderer.py path/to/briefing.md
"""

from __future__ import annotations

import html
import re
import sys
from pathlib import Path

import markdown2


def strip_frontmatter(text: str) -> str:
    """Remove YAML frontmatter (between --- delimiters)."""
    if text.startswith("---"):
        end = text.find("---", 3)
        if end != -1:
            return text[end + 3:].lstrip("\n")
    return text


def strip_obsidian_syntax(text: str) -> str:
    """Remove Obsidian-specific markdown syntax."""
    # Wikilinks: [[Page Name]] -> Page Name, [[Page Name|Display]] -> Display
    text = re.sub(r"\[\[([^|\]]+)\|([^\]]+)\]\]", r"\2", text)
    text = re.sub(r"\[\[([^\]]+)\]\]", r"\1", text)
    # Callouts: > [!note] -> (remove callout markers, keep content)
    text = re.sub(r"^> \[!(\w+)\].*$", "", text, flags=re.MULTILINE)
    # Embeds: ![[filename]] -> (remove)
    text = re.sub(r"!\[\[([^\]]+)\]\]", "", text)
    return text


def wrap_html_email(html_body: str, title: str) -> str:
    """Wrap HTML content in a responsive email template."""
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
  body {{
    margin: 0;
    padding: 0;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, Helvetica, sans-serif;
    font-size: 15px;
    line-height: 1.6;
    color: #1a1a1a;
    background-color: #f5f5f5;
  }}
  @media (prefers-color-scheme: dark) {{
    body {{ background-color: #1a1a1a; color: #e0e0e0; }}
    .container {{ background-color: #2d2d2d; }}
    table {{ border-color: #444; }}
    th {{ background-color: #383838; color: #e0e0e0; }}
    td {{ border-color: #444; }}
    tr:nth-child(even) {{ background-color: #333; }}
    a {{ color: #6db3f2; }}
    h1, h2, h3 {{ color: #f0f0f0; }}
    .header {{ background-color: #1e3a5f; }}
  }}
  .container {{
    max-width: 700px;
    margin: 0 auto;
    padding: 20px;
    background-color: #ffffff;
  }}
  .header {{
    background-color: #1a365d;
    color: #ffffff;
    padding: 16px 20px;
    border-radius: 6px 6px 0 0;
    margin: -20px -20px 20px -20px;
  }}
  .header h1 {{
    margin: 0;
    font-size: 20px;
    font-weight: 600;
    color: #ffffff;
  }}
  .header p {{
    margin: 4px 0 0 0;
    font-size: 13px;
    opacity: 0.85;
    color: #cbd5e0;
  }}
  h2 {{
    font-size: 17px;
    font-weight: 600;
    margin: 24px 0 12px 0;
    padding-bottom: 6px;
    border-bottom: 2px solid #e2e8f0;
    color: #1a365d;
  }}
  h3 {{
    font-size: 15px;
    font-weight: 600;
    margin: 18px 0 8px 0;
    color: #2d3748;
  }}
  table {{
    width: 100%;
    border-collapse: collapse;
    margin: 12px 0;
    font-size: 13px;
  }}
  th {{
    background-color: #f7fafc;
    font-weight: 600;
    text-align: left;
    padding: 8px 10px;
    border: 1px solid #e2e8f0;
    color: #4a5568;
    font-size: 12px;
    text-transform: uppercase;
    letter-spacing: 0.5px;
  }}
  td {{
    padding: 7px 10px;
    border: 1px solid #e2e8f0;
    vertical-align: top;
  }}
  tr:nth-child(even) {{
    background-color: #f7fafc;
  }}
  ul, ol {{
    padding-left: 20px;
    margin: 8px 0;
  }}
  li {{
    margin: 4px 0;
  }}
  code {{
    background-color: #edf2f7;
    padding: 2px 5px;
    border-radius: 3px;
    font-size: 13px;
    font-family: 'SF Mono', Monaco, Consolas, monospace;
  }}
  a {{
    color: #2b6cb0;
    text-decoration: none;
  }}
  a:hover {{
    text-decoration: underline;
  }}
  .footer {{
    margin-top: 24px;
    padding-top: 12px;
    border-top: 1px solid #e2e8f0;
    font-size: 12px;
    color: #a0aec0;
    text-align: center;
  }}
  input[type="checkbox"] {{
    margin-right: 6px;
  }}
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>{title}</h1>
    <p>Generated by Stock Briefing Skill</p>
  </div>
  {html_body}
  <div class="footer">
    Delivered by Claude Code &middot; Stock Briefing Skill v1.0
  </div>
</div>
</body>
</html>"""


def main() -> int:
    # Ensure stdout is UTF-8 on Windows
    if sys.stdout.encoding != "utf-8":
        sys.stdout.reconfigure(encoding="utf-8")

    if len(sys.argv) < 2:
        print("Usage: email_renderer.py <path-to-markdown-file>", file=sys.stderr)
        return 1

    md_path = Path(sys.argv[1])
    if not md_path.exists():
        print(f"File not found: {md_path}", file=sys.stderr)
        return 1

    text = md_path.read_text(encoding="utf-8")
    text = strip_frontmatter(text)
    text = strip_obsidian_syntax(text)

    # Convert markdown to HTML
    html_body = markdown2.markdown(
        text,
        extras=["tables", "fenced-code-blocks", "task_list", "strike"],
    )

    # Extract title from first H1 and escape for safe HTML insertion
    title_match = re.search(r"^#\s+(.+)$", text, re.MULTILINE)
    title = html.escape(title_match.group(1) if title_match else "Portfolio Briefing")

    full_html = wrap_html_email(html_body, title)
    print(full_html)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
